### ISSUE TITLE
省_设置上报期_js/php_没有条件检查

### ISSUE THREAD

**Issue by diwujiahao** [nmchgx/CM-Git#9]
详细描述：新增 schedule 的上报期需要条件检查：1、上报开始时间 < 上报截止时间 2、同一个月份只能有一个上报期   3、检查 本月的”上报开始时间“和”截止时间“只能在本月内
负责人：陈高勋/邱岳诗
状态：未修复

**Comment by VickyTse** [comment]
php已修复

**Comment by nmchgx** [comment]
已修复

**Comment by nmchgx** [comment]
已修复
